services:
  pan123:
    image: python:3.13.4
    container_name: pan123
    ports:
      # 主机外部端口:容器内部端口
      - "33333:33333"
    volumes:
      # 映射主机上的日志目录到容器内
      # 请确保 /DOCKER/123Pan-Unlimited-Share/logs 目录在主机上存在
      - /DOCKER/123Pan-Unlimited-Share/logs:/app/external/logs
      # 映射自己的配置文件
      # 请确保 /DOCKER/123Pan-Unlimited-Share/settings.yaml 文件在主机上存在
      - /DOCKER/123Pan-Unlimited-Share/settings.yaml:/app/external/settings.yaml:ro
      # 映射自己的数据库文件
      # 请确保 /DOCKER/123Pan-Unlimited-Share/PAN123DATABASE.db 文件在主机上存在
      - /DOCKER/123Pan-Unlimited-Share/PAN123DATABASE.db:/app/external/PAN123DATABASE.db
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
    working_dir: /app
    command: >
      sh -c "
        set -e &&
        echo 'INFO: Updating package list and installing git and wget...' &&
        apt-get update && apt-get install -y git wget && rm -rf /var/lib/apt/lists/* &&
        
        echo 'INFO: Managing source code repository in /app/source...' &&
        if [ -d 'source/.git' ]; then
          echo 'INFO: Repository exists. Pulling latest changes...' &&
          cd source && git pull && cd .. ;
        else
          if [ -d 'source' ]; then
            echo 'INFO: Removing incomplete source directory...' &&
            rm -rf source ;
          fi
          echo 'INFO: Cloning repository into ./source...' &&
          git clone https://ghfast.top/https://github.com/realcwj/123Pan-Unlimited-Share.git source ;
        fi &&
        
        cd source &&
        
        echo 'INFO: Linking persistent config and logs into the source directory...' &&

        ln -sf /app/external/settings.yaml settings.yaml &&
        ln -sf /app/external/logs logs &&
        ln -sf /app/external/PAN123DATABASE.db assets/PAN123DATABASE.db &&
        
        echo 'INFO: Installing requirements from requirements.txt...' &&
        pip install --no-cache-dir -r requirements.txt &&
        
        echo 'INFO: Installing gunicorn...' &&
        pip install --no-cache-dir gunicorn &&
        
        echo 'INFO: Creating assets directory if it does not exist...' &&
        mkdir -p assets &&

        echo 'INFO: Starting Gunicorn server...' &&

        exec gunicorn -c gunicorn.conf.py web:app
      "